services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./app:/home/node/portfolio
    ports:
      - 3000:3000
      - 6006:6006
